image: "Visual Studio 2017"

clone_folder: c:\projects\UDM
environment:
  UDM_PATH: c:\projects\UDM
  UDM_3RDPARTY_PATH: c:\projects\UDM-3rdparty
  GME_ROOT: c:\Program Files (x86)\GME

install:
#  - choco install -y wixtoolset -version 3.9.1208.0
#  - ps: (new-object net.webclient).DownloadFile('https://wix.codeplex.com/downloads/get/1421696', 'c:\wix39.exe')
#  - c:\wix39.exe -silent
#  - type C:\ProgramData\chocolatey\logs\chocolatey.log
#  - dir /b/s \ | %windir%\system32\find "WiX Toolset"
#  - dir /b/s C:\MinGW
  - reg query "HKLM\SOFTWARE\Microsoft\Windows Installer XML" /reg:32
  - reg query "HKLM\SOFTWARE\Microsoft\Windows Installer XML\3.11" /reg:32
  - ps: (new-object net.webclient).DownloadFile('https://github.com/ksmyth/UDM/tarball/3rdparty', 'c:\3rdparty.tar.gz')
  - mkdir c:\projects\UDM-3rdparty
  - C:\msys64\usr\bin\bsdtar.exe xzf /c/3rdparty.tar.gz -C /c/projects/UDM-3rdparty --strip-components=1
  - dir c:\projects\UDM-3rdparty\GME_x64-17.12.6.msi
  - msiexec /i c:\projects\UDM-3rdparty\GME_x64-17.12.6.msi /quiet /qn /norestart /log GME_install.log
#  - type GME_install.log
#  - ps: (new-object net.webclient).DownloadFile('https://github.com/ksmyth/pywin32/releases/download/b219/pywin32-219.win32-py2.7.exe', 'c:\pywin32-219.win32-py2.7.exe')
#  - python -m easy_install c:\pywin32-219.win32-py2.7.exe
  - ps: (new-object net.webclient).DownloadFile('https://nuget-packages.metamorphsoftware.com/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
  - ps: $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
  - ps: Import-Module CoApp

build_script:
  - Projects\Win32\VC10\src\.nuget\NuGet.exe restore -Source https://www.nuget.org/api/v2 Projects\Win32\VC10\src\Udmv141.sln
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" make.msbuild /m /t:BuildVC15;BuildVC15_x64 /p:"VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets";PlatformToolset=v141'
  - ps: 'Import-Module CoApp; Write-NuGetPackage .\Udm-vc141.autopkg'

artifacts:
  - path: "*.nupkg"
  - path: "*.log"
  - path: "WiX/*/*.wixlib"
  - path: src/UdmPython/dist/*.whl
