#SUBDIRS =test_UdmPython 
SUBDIRS =test_generic test_generic2 test_libs test_simpleudmops testGetAdjacentObjects testOCL test_childrenorder testUdmCint test_cintstring  test_crosslinks test_ns test_ns2 test_refports test_domstringdn


all:
	@for dir in $(SUBDIRS);\
	do \
		echo "\nInvoking make in subdir: " $${dir};\
		$(MAKE) -C $${dir} $@ -f Makefile.OSX || exit $$?;\
	done
test:
	@for dir in $(SUBDIRS);\
	do \
		echo "\nInvoking make clean in subdir: " $${dir};\
		$(MAKE) test  -C $${dir} $@ -f Makefile.OSX || exit $$?;\
	done

clean:
	@for dir in $(SUBDIRS);\
	do \
		echo "\nInvoking make clean in subdir: " $${dir};\
		$(MAKE) clean -C $${dir} $@ -f Makefile.OSX ;\
	done


