include ../../../../../Makefile.OSX.incl

SOURCES= AParser.cpp ATokenBuffer.cpp DLexerBase.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) $(OBJECTS)

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@
clean: 
	rm -f *.o
