include ../../../Makefile.OSX.incl

SOURCES=ClassGen.cpp	FactoryGen.cpp	JavaAPIGen.cpp	Utils.cpp	UtilsGen.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) $(OBJECTS)

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@
clean: 
	rm -f *.o

