include ../../Makefile.OSX.incl

SOURCES=cintUdmPseudoTest.cpp	test_cintudmpseudo.cpp LampDiagram.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) $(OBJECTS) test_cintpseudo

LampDiagram.cpp:../../samples/LampDiagram_udm.xml ../../bin/Udm
	DYLD_LIBRARY_PATH=$(DYLDLIBRARYPATH) ../../bin/Udm $< -v -d ../../etc -T
.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDE) -I $(CPPUNIT)/include $< -o $@

test_cintpseudo: $(OBJECTS)
	$(CC) $(BCFLAGS) $(OBJECTS) -o test_cintpseudo  -lUdm -L../../lib -lcppunit -L $(CPPUNITLIBS)

test:test_cintpseudo
	DYLD_LIBRARY_PATH=$(DYLDLIBRARYPATH) ./test_cintpseudo

clean: 
	rm -f *.o  test_cintpseudo LampDiagram.cpp LampDiagram.h LampDiagram.xsd *.mem *.xml
