include ../../Makefile.OSX.incl

SOURCES=DTDGen.cpp	Project.cpp	UdmBase.cpp	UdmProject.cpp	UdmStatic.cpp	UdmTomi.cpp	UmlExt.cpp	cint_string.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) $(OBJECTS)

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@
clean: 
	rm -f *.o
