SUBDIRS =CreateLampModel cross_links

all:
	@for dir in $(SUBDIRS);\
	do \
		echo "\nInvoking make in subdir: " $${dir};\
		$(MAKE) -C $${dir} $@ -f Makefile.OSX || exit $$?;\
	done

clean:
	@for dir in $(SUBDIRS);\
	do \
		echo "\nInvoking make clean in subdir: " $${dir};\
		$(MAKE) clean -C $${dir} $@ -f Makefile.OSX ;\
	done

