include ../../Makefile.OSX.incl

SOURCES=UdmOcl.cpp		UdmOclObject.cpp	UdmOclType.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) $(OBJECTS)

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDE) $< -o $@
clean: 
	rm -f *.o
